#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Theme {
    Light,
    Dark,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Locale {
    En,
    Zh,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AppSettings {
    pub theme: Theme,
    pub locale: Locale,
}

impl AppSettings {
    pub fn new() -> Self {
        Self {
            theme: Theme::Light,
            locale: Locale::Zh,
        }
    }
}

pub fn t(key: &str, locale: Locale) -> &'static str {
    match (key, locale) {
        // Sidebar
        ("sidebar.dashboard", Locale::Zh) => "仪表盘",
        ("sidebar.dashboard", Locale::En) => "Dashboard",
        ("sidebar.marketplace", Locale::Zh) => "Skill市场",
        ("sidebar.marketplace", Locale::En) => "Marketplace",
        ("sidebar.library", Locale::Zh) => "技能库",
        ("sidebar.library", Locale::En) => "Library",
        ("sidebar.all_skills", Locale::Zh) => "所有技能",
        ("sidebar.all_skills", Locale::En) => "All Skills",
        ("sidebar.enabled", Locale::Zh) => "已启用",
        ("sidebar.enabled", Locale::En) => "Enabled",
        ("sidebar.disabled", Locale::Zh) => "已禁用",
        ("sidebar.disabled", Locale::En) => "Disabled",
        ("sidebar.source", Locale::Zh) => "来源",
        ("sidebar.source", Locale::En) => "Source",
        ("sidebar.my_skills", Locale::Zh) => "我创建的",
        ("sidebar.my_skills", Locale::En) => "My Skills",
        ("sidebar.downloaded", Locale::Zh) => "社区获取",
        ("sidebar.downloaded", Locale::En) => "Downloaded",
        ("sidebar.linked", Locale::Zh) => "已链接",
        ("sidebar.linked", Locale::En) => "Linked",
        ("sidebar.other", Locale::Zh) => "其他",
        ("sidebar.other", Locale::En) => "Other",
        ("sidebar.theme_light", Locale::Zh) => "浅色",
        ("sidebar.theme_light", Locale::En) => "Light",
        ("sidebar.theme_dark", Locale::Zh) => "深色",
        ("sidebar.theme_dark", Locale::En) => "Dark",
        ("sidebar.lang", Locale::Zh) => "语言",
        ("sidebar.lang", Locale::En) => "Language",

        // Search bar
        ("search.upload", Locale::Zh) => "上传",
        ("search.upload", Locale::En) => "Upload",
        ("search.placeholder", Locale::Zh) => "搜索技能...",
        ("search.placeholder", Locale::En) => "filter skills...",
        ("search.skills_count", Locale::Zh) => "个技能",
        ("search.skills_count", Locale::En) => "skills",

        // Card
        ("card.from", Locale::Zh) => "来自",
        ("card.from", Locale::En) => "from",
        ("card.my_skill", Locale::Zh) => "我创建的",
        ("card.my_skill", Locale::En) => "My Skill",
        ("card.downloaded", Locale::Zh) => "社区获取",
        ("card.downloaded", Locale::En) => "Downloaded",
        ("card.linked", Locale::Zh) => "已链接",
        ("card.linked", Locale::En) => "Linked",
        ("card.file", Locale::Zh) => "文件",
        ("card.file", Locale::En) => "File",
        ("card.files", Locale::Zh) => "个文件",
        ("card.files", Locale::En) => "files",
        ("card.disable", Locale::Zh) => "禁用",
        ("card.disable", Locale::En) => "Disable",
        ("card.enable", Locale::Zh) => "启用",
        ("card.enable", Locale::En) => "Enable",

        // Grid
        ("grid.selected", Locale::Zh) => "已选择",
        ("grid.selected", Locale::En) => "selected",
        ("grid.select_all", Locale::Zh) => "全选",
        ("grid.select_all", Locale::En) => "Select All",
        ("grid.delete", Locale::Zh) => "删除",
        ("grid.delete", Locale::En) => "Delete",

        // Dashboard
        ("dashboard.title", Locale::Zh) => "仪表盘",
        ("dashboard.title", Locale::En) => "Dashboard",
        ("dashboard.total_skills", Locale::Zh) => "技能总数",
        ("dashboard.total_skills", Locale::En) => "Total Skills",
        ("dashboard.enabled", Locale::Zh) => "已启用",
        ("dashboard.enabled", Locale::En) => "Enabled",
        ("dashboard.disabled", Locale::Zh) => "已禁用",
        ("dashboard.disabled", Locale::En) => "Disabled",
        ("dashboard.files", Locale::Zh) => "个文件",
        ("dashboard.files", Locale::En) => "files",
        ("dashboard.my_skills", Locale::Zh) => "我创建的",
        ("dashboard.my_skills", Locale::En) => "My Skills",
        ("dashboard.downloaded", Locale::Zh) => "社区获取",
        ("dashboard.downloaded", Locale::En) => "Downloaded",
        ("dashboard.linked", Locale::Zh) => "已链接",
        ("dashboard.linked", Locale::En) => "Linked",
        ("dashboard.file", Locale::Zh) => "文件",
        ("dashboard.file", Locale::En) => "File",
        ("dashboard.panel_growth", Locale::Zh) => "增长趋势",
        ("dashboard.panel_growth", Locale::En) => "growth-trend.svg",
        ("dashboard.panel_source", Locale::Zh) => "来源分布",
        ("dashboard.panel_source", Locale::En) => "source-breakdown.md",
        ("dashboard.panel_largest", Locale::Zh) => "体积排行",
        ("dashboard.panel_largest", Locale::En) => "largest-skills.log",
        ("dashboard.panel_recent", Locale::Zh) => "最近活动",
        ("dashboard.panel_recent", Locale::En) => "recent-activity.log",
        ("dashboard.no_chart_data", Locale::Zh) => "日期数据不足，无法渲染图表",
        ("dashboard.no_chart_data", Locale::En) => "Not enough date info to render chart",
        ("dashboard.chart_note", Locale::Zh) => "基于技能安装时间，累计数量",
        ("dashboard.chart_note", Locale::En) => "Based on skill install time, cumulative count",
        ("dashboard.no_dates", Locale::Zh) => "无安装日期信息",
        ("dashboard.no_dates", Locale::En) => "No install dates available",
        ("dashboard.skills_label", Locale::Zh) => "技能数",
        ("dashboard.skills_label", Locale::En) => "Skills",

        // Marketplace
        ("marketplace.search_title", Locale::Zh) => "搜索技能",
        ("marketplace.search_title", Locale::En) => "Search skills",
        ("marketplace.sort_by", Locale::Zh) => "排序方式",
        ("marketplace.sort_by", Locale::En) => "Sort by",
        ("marketplace.stars", Locale::Zh) => "收藏",
        ("marketplace.stars", Locale::En) => "Stars",
        ("marketplace.recent", Locale::Zh) => "最新",
        ("marketplace.recent", Locale::En) => "Recent",
        ("marketplace.placeholder", Locale::Zh) => "搜索 'code review', 'git automation'...",
        ("marketplace.placeholder", Locale::En) => "try 'code review', 'git automation', 'data analysis'...",
        ("marketplace.no_results", Locale::Zh) => "未找到技能",
        ("marketplace.no_results", Locale::En) => "No skills found",
        ("marketplace.end", Locale::Zh) => "-- 已无更多结果 --",
        ("marketplace.end", Locale::En) => "-- end of results --",
        ("marketplace.install", Locale::Zh) => "安装",
        ("marketplace.install", Locale::En) => "Install",

        // Drawer
        ("drawer.skill_details", Locale::Zh) => "技能详情",
        ("drawer.skill_details", Locale::En) => "Skill Details",
        ("drawer.disabled_label", Locale::Zh) => "已禁用",
        ("drawer.disabled_label", Locale::En) => "DISABLED",
        ("drawer.disable", Locale::Zh) => "禁用",
        ("drawer.disable", Locale::En) => "Disable",
        ("drawer.enable", Locale::Zh) => "启用",
        ("drawer.enable", Locale::En) => "Enable",
        ("drawer.mark_downloaded", Locale::Zh) => "标记为社区获取",
        ("drawer.mark_downloaded", Locale::En) => "Mark as Downloaded",
        ("drawer.mark_custom", Locale::Zh) => "标记为我创建的",
        ("drawer.mark_custom", Locale::En) => "Mark as My Skill",
        ("drawer.delete", Locale::Zh) => "删除",
        ("drawer.delete", Locale::En) => "Delete",
        ("drawer.remove_link", Locale::Zh) => "移除链接",
        ("drawer.remove_link", Locale::En) => "Remove Link",
        ("drawer.stat_cmd", Locale::Zh) => "stat --summary",
        ("drawer.stat_cmd", Locale::En) => "stat --summary",
        ("drawer.files_label", Locale::Zh) => "文件:",
        ("drawer.files_label", Locale::En) => "files:",
        ("drawer.size", Locale::Zh) => "大小:",
        ("drawer.size", Locale::En) => "size:",
        ("drawer.tier", Locale::Zh) => "层级:",
        ("drawer.tier", Locale::En) => "tier:",
        ("drawer.file_explorer", Locale::Zh) => "文件浏览器",
        ("drawer.file_explorer", Locale::En) => "File Explorer",
        ("drawer.readonly", Locale::Zh) => "只读",
        ("drawer.readonly", Locale::En) => "readonly",
        ("drawer.lines", Locale::Zh) => "行",
        ("drawer.lines", Locale::En) => "lines",
        ("drawer.install_skill", Locale::Zh) => "安装技能",
        ("drawer.install_skill", Locale::En) => "Install Skill",
        ("drawer.stars", Locale::Zh) => "收藏:",
        ("drawer.stars", Locale::En) => "stars:",
        ("drawer.forks", Locale::Zh) => "分支:",
        ("drawer.forks", Locale::En) => "forks:",
        ("drawer.updated", Locale::Zh) => "更新于:",
        ("drawer.updated", Locale::En) => "updated:",

        // Upload
        ("upload.title", Locale::Zh) => "上传技能",
        ("upload.title", Locale::En) => "Upload Skill",
        ("upload.preview_title", Locale::Zh) => "预览技能",
        ("upload.preview_title", Locale::En) => "Preview Skill",
        ("upload.drop_release", Locale::Zh) => "松开以上传",
        ("upload.drop_release", Locale::En) => "Release to upload",
        ("upload.drop_hint", Locale::Zh) => "拖拽文件到此处或点击选择",
        ("upload.drop_hint", Locale::En) => "Drag file here or click to select",
        ("upload.requirements", Locale::Zh) => "文件要求",
        ("upload.requirements", Locale::En) => "File requirements",
        ("upload.req_md", Locale::Zh) => ".md 文件必须在 YAML 前言中包含 name 和 description",
        ("upload.req_md", Locale::En) => ".md file must contain name and description in YAML frontmatter",
        ("upload.req_zip", Locale::Zh) => ".zip 文件必须包含 SKILL.md 文件",
        ("upload.req_zip", Locale::En) => ".zip file must include a SKILL.md file",
        ("upload.added_by", Locale::Zh) => "添加者",
        ("upload.added_by", Locale::En) => "Added by",
        ("upload.you", Locale::Zh) => "你",
        ("upload.you", Locale::En) => "You",
        ("upload.last_updated", Locale::Zh) => "上次更新",
        ("upload.last_updated", Locale::En) => "Last updated",
        ("upload.tier", Locale::Zh) => "层级",
        ("upload.tier", Locale::En) => "Tier",
        ("upload.license", Locale::Zh) => "许可",
        ("upload.license", Locale::En) => "License",
        ("upload.description", Locale::Zh) => "描述",
        ("upload.description", Locale::En) => "Description",
        ("upload.install", Locale::Zh) => "安装技能",
        ("upload.install", Locale::En) => "Install Skill",

        // Confirm dialog
        ("dialog.cancel", Locale::Zh) => "取消",
        ("dialog.cancel", Locale::En) => "Cancel",
        ("dialog.delete_skill", Locale::Zh) => "删除技能",
        ("dialog.delete_skill", Locale::En) => "Delete Skill",
        ("dialog.delete_linked", Locale::Zh) => "删除已链接技能",
        ("dialog.delete_linked", Locale::En) => "Delete Linked Skill",
        ("dialog.remove_link_only", Locale::Zh) => "仅移除链接",
        ("dialog.remove_link_only", Locale::En) => "Remove Link Only",
        ("dialog.delete_completely", Locale::Zh) => "完全删除",
        ("dialog.delete_completely", Locale::En) => "Delete Completely",
        ("dialog.move_to_trash", Locale::Zh) => "将 '{}' 移到废纸篓？",
        ("dialog.move_to_trash", Locale::En) => "Move '{}' to trash?",
        ("dialog.is_symlink", Locale::Zh) => "'{}' 是一个符号链接。",
        ("dialog.is_symlink", Locale::En) => "'{}' is a symlink.",
        ("dialog.symlink_confirm", Locale::Zh) => "'{}' 是一个符号链接。仅移除链接，还是同时删除原始文件？",
        ("dialog.symlink_confirm", Locale::En) => "'{}' is a symlink. Remove the link only, or delete the original files too?",
        ("dialog.delete_confirm", Locale::Zh) => "删除 '{}' 及其所有文件？此操作不可撤销。",
        ("dialog.delete_confirm", Locale::En) => "Delete '{}' and all its files? This cannot be undone.",

        // Badge
        ("badge.my_skill", Locale::Zh) => "我创建的",
        ("badge.my_skill", Locale::En) => "My Skill",
        ("badge.downloaded", Locale::Zh) => "社区获取",
        ("badge.downloaded", Locale::En) => "Downloaded",
        ("badge.linked", Locale::Zh) => "已链接",
        ("badge.linked", Locale::En) => "Linked",
        ("badge.file", Locale::Zh) => "文件",
        ("badge.file", Locale::En) => "File",
        ("badge.enabled", Locale::Zh) => "已启用",
        ("badge.enabled", Locale::En) => "Enabled",
        ("badge.disabled", Locale::Zh) => "已禁用",
        ("badge.disabled", Locale::En) => "Disabled",

        // Detail page
        ("detail.back", Locale::Zh) => "返回",
        ("detail.back", Locale::En) => "Back",
        ("detail.disable", Locale::Zh) => "禁用",
        ("detail.disable", Locale::En) => "Disable",
        ("detail.enable", Locale::Zh) => "启用",
        ("detail.enable", Locale::En) => "Enable",
        ("detail.edit", Locale::Zh) => "编辑",
        ("detail.edit", Locale::En) => "Edit",
        ("detail.mark_downloaded", Locale::Zh) => "标记为社区获取",
        ("detail.mark_downloaded", Locale::En) => "Mark as Downloaded",
        ("detail.mark_custom", Locale::Zh) => "标记为我创建的",
        ("detail.mark_custom", Locale::En) => "Mark as My Skill",
        ("detail.remove_link", Locale::Zh) => "移除链接",
        ("detail.remove_link", Locale::En) => "Remove Link",
        ("detail.delete", Locale::Zh) => "删除",
        ("detail.delete", Locale::En) => "Delete",
        ("detail.metadata", Locale::Zh) => "元数据",
        ("detail.metadata", Locale::En) => "Metadata",
        ("detail.name", Locale::Zh) => "名称",
        ("detail.name", Locale::En) => "Name",
        ("detail.files", Locale::Zh) => "文件",
        ("detail.files", Locale::En) => "Files",
        ("detail.size", Locale::Zh) => "大小",
        ("detail.size", Locale::En) => "Size",
        ("detail.preamble_tier", Locale::Zh) => "前言层级",
        ("detail.preamble_tier", Locale::En) => "Preamble Tier",
        ("detail.license", Locale::Zh) => "许可",
        ("detail.license", Locale::En) => "License",
        ("detail.argument_hint", Locale::Zh) => "参数提示",
        ("detail.argument_hint", Locale::En) => "Argument Hint",
        ("detail.allowed_tools", Locale::Zh) => "允许的工具",
        ("detail.allowed_tools", Locale::En) => "Allowed Tools",
        ("detail.description", Locale::Zh) => "描述",
        ("detail.description", Locale::En) => "Description",
        ("detail.content", Locale::Zh) => "内容",
        ("detail.content", Locale::En) => "Content",
        ("detail.files_count", Locale::Zh) => "文件",
        ("detail.files_count", Locale::En) => "Files",
        ("detail.not_found", Locale::Zh) => "未找到技能",
        ("detail.not_found", Locale::En) => "Skill not found",
        ("detail.back_to_list", Locale::Zh) => "返回列表",
        ("detail.back_to_list", Locale::En) => "Back to list",

        // Edit form
        ("form.back", Locale::Zh) => "返回",
        ("form.back", Locale::En) => "Back",
        ("form.name", Locale::Zh) => "名称",
        ("form.name", Locale::En) => "Name",
        ("form.description", Locale::Zh) => "描述",
        ("form.description", Locale::En) => "Description",
        ("form.version", Locale::Zh) => "版本",
        ("form.version", Locale::En) => "Version",
        ("form.body", Locale::Zh) => "正文 (Markdown)",
        ("form.body", Locale::En) => "Body (Markdown)",
        ("form.save", Locale::Zh) => "保存",
        ("form.save", Locale::En) => "Save",
        ("form.cancel", Locale::Zh) => "取消",
        ("form.cancel", Locale::En) => "Cancel",
        ("form.not_found", Locale::Zh) => "未找到技能。",
        ("form.not_found", Locale::En) => "Skill not found.",

        // Toast messages
        ("toast.installed", Locale::Zh) => "'{}' 已安装！",
        ("toast.installed", Locale::En) => "'{}' installed!",
        ("toast.unsupported_file", Locale::Zh) => "不支持的文件类型。请使用 .md 或 .zip",
        ("toast.unsupported_file", Locale::En) => "Unsupported file type. Use .md or .zip",
        ("toast.load_failed", Locale::Zh) => "加载内容失败。",
        ("toast.load_failed", Locale::En) => "Failed to load content.",
        ("toast.fetch_failed", Locale::Zh) => "获取内容失败",
        ("toast.fetch_failed", Locale::En) => "Failed to fetch content",
        ("toast.file_too_large", Locale::Zh) => "[文件过大，无法预览 (>1MB)]",
        ("toast.file_too_large", Locale::En) => "[File too large to preview (>1MB)]",
        ("toast.binary_file", Locale::Zh) => "[二进制或不可读文件]",
        ("toast.binary_file", Locale::En) => "[Binary or unreadable file]",

        // Marketplace misc
        ("marketplace.unknown_author", Locale::Zh) => "未知",
        ("marketplace.unknown_author", Locale::En) => "Unknown",

        // Empty state
        ("empty.not_detected", Locale::Zh) => "未检测到 Claude Code",
        ("empty.not_detected", Locale::En) => "Claude Code not detected",
        ("empty.install_first", Locale::Zh) => "请先安装 Claude Code，之后你的技能将自动显示在这里。",
        ("empty.install_first", Locale::En) => "Install Claude Code first, then your skills will appear here automatically.",
        ("empty.no_skills", Locale::Zh) => "暂无技能",
        ("empty.no_skills", Locale::En) => "No skills yet",
        ("empty.browse_hint", Locale::Zh) => "浏览市场发现技能，或上传你自己的技能。",
        ("empty.browse_hint", Locale::En) => "Browse the Marketplace to discover skills, or upload your own.",
        ("empty.no_match", Locale::Zh) => "没有匹配的技能",
        ("empty.no_match", Locale::En) => "No skills match your search",
        ("empty.no_found", Locale::Zh) => "未找到技能",
        ("empty.no_found", Locale::En) => "No skills found",

        // Not found
        ("notfound.message", Locale::Zh) => "页面未找到",
        ("notfound.message", Locale::En) => "Page not found",

        // About / Branding
        ("about.tagline", Locale::Zh) => "免费软件 · 不可商业化 · 抖音号: 54927876676",
        ("about.tagline", Locale::En) => "Free Software · Non-Commercial · Douyin: 54927876676",

        // Welcome dialog
        ("welcome.free_notice", Locale::Zh) => "本软件完全免费，仅供个人学习和非商业用途。严禁任何形式的商业化行为，包括但不限于出售、收费分发、嵌入付费产品等。",
        ("welcome.free_notice", Locale::En) => "This software is completely free for personal and non-commercial use. Any form of commercialization is strictly prohibited, including selling, paid distribution, or embedding in paid products.",
        ("welcome.scam_warning", Locale::Zh) => "如果你是花钱买到的这个软件，你被骗了，请举报卖家。",
        ("welcome.scam_warning", Locale::En) => "If you paid for this software, you were scammed. Please report the seller.",
        ("welcome.douyin", Locale::Zh) => "抖音搜索「Winhao学AI」",
        ("welcome.douyin", Locale::En) => "Douyin: Winhao学AI",
        ("welcome.dismiss", Locale::Zh) => "我知道了",
        ("welcome.dismiss", Locale::En) => "Got it",

        _ => "???",
    }
}
